name: CI/CD - Testes Automatizados

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Escolha a branch para executar os testes'
        required: true
        default: 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Executar testes automatizados
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Instalar Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Instalar dependências e compilar
        run: mvn clean install -DskipTests

      - name: Executar testes
        run: mvn -Dtest=RunnerAllTest test

      - name: Gerar Allure Report
        run: mvn io.qameta.allure:allure-maven:2.15.0:report

      - name: Salvar Allure Results como artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Salvar Allure Report como artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

  deploy-report:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' }}
    name: Publicar Allure Report no GitHub Pages
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Instalar Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Baixar Allure Report gerado
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Publicar Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
